print("Hello, Git!")
print("I am learning Git step by step.")
print("Git is useful for version control.")
print("I am learning GitHub.")
print("This change is only on my feature branch.")
print("Learning branches hands-on.")
print("I am revising Git.")
